### ISSUE TITLE
 CMakeLists.txt.in 'GIT_TAG master' is outdated

### ISSUE THREAD

**Issue by Crazyayane07** [coders-school/pizzas#44]
Fixed by changing master to main.
Pull request: https://github.com/coders-school/pizzas/pull/43
Resolution source: https://github.com/google/googletest/issues/3663

**Comment by ziobron** [comment]
🏅 2 XP granted for @Crazyayane07
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Global replacement in all @coders-school repos is planned in the next week.

**Comment by ziobron** [comment]
Fixed
